# Ref.: https://docs.gitlab.com/ee/ci/caching/index.html#cache-python-dependencies
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  stage: deploy
  image: python:3.11-bullseye

  tags:
    - builder

  script:
    - pip install .
    - cd docs
    - pip install -r docs-requirements.txt
    - make html
    - cd source
    - sphinx-build -b html . ../../public

  artifacts:
    paths:
      - public
